spring:
  application:
    name: redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: password
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: -1ms
